[package]
name = "prototype"
version = "0.1.0"

edition.workspace = true
version.workspace = true
authors.workspace = true

[dependencies]
bevy.workspace = true
rand.workspace = true
bevy_sprite = "0.16.1"
